import * as Mocha from 'mocha';
import { expect, assert } from 'chai';
import { Filter, Account, AccountSettings, AuthorizedApp, Backup, CreditCard, Device, Devices, Disk, DiskRequest, Domain, DomainRecord, ErrorObject, Event, Grant, GrantsResponse, ImagePrivate, ImagePublic, Invoice, InvoiceItem, IPAddress, IPAddressPrivate, IPAddressV6LinkLocal, IPAddressV6Slaac, IPv6Pool, IPv6Range, Kernel, Linode, LinodeBase, LinodeConfig, LinodeRequest, LinodeStats, LinodeType, LongviewClient, LongviewSubscription, ManagedContact, ManagedCredential, ManagedIssue, ManagedLinodeSettings, ManagedService, NodeBalancer, NodeBalancerConfig, NodeBalancerNode, Notification, OAuthClient, PaginationEnvelope, Payment, PaymentRequest, PayPal, PayPalExecute, PersonalAccessToken, Profile, Region, RescueDevices, StackScript, SupportTicket, SupportTicketReply, SupportTicketRequest, Transfer, User, UserDefinedField, Volume, AuthorizedAppFilter, DiskFilter, DiskRequestFilter, DomainFilter, ImagePrivateFilter, ImagePublicFilter, IPAddressFilter, IPAddressPrivateFilter, IPAddressV6LinkLocalFilter, IPAddressV6SlaacFilter, KernelFilter, LinodeFilter, LinodeBaseFilter, LinodeConfigFilter, LinodeTypeFilter, LongviewClientFilter, ManagedContactFilter, NodeBalancerFilter, OAuthClientFilter, PersonalAccessTokenFilter, StackScriptFilter, SupportTicketFilter, UserFilter, VolumeFilter } from '../src/interfaces';
import { Linodev4 } from '../src/'
const server = new Linodev4('personal-key-secured', async (data) => Promise.resolve(data) );
describe('/support', () => {
	it('tickets', async ()=>{
		expect(await server.support.tickets.list()).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets.list(1)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets","query":"?page=1","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets.list(1, 50)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets","query":"?page=1&page_size=50","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets.list({} as Filter<SupportTicketFilter>)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets","headers":{"Authorization":"Bearer personal-key-secured","X-Filter":{}}});
		expect(await server.support.tickets.list(2, {} as Filter<SupportTicketFilter>)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets","query":"?page=2","headers":{"Authorization":"Bearer personal-key-secured","X-Filter":{}}});
		expect(await server.support.tickets.list(2, 5, {} as Filter<SupportTicketFilter>)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets","query":"?page=2&page_size=5","headers":{"Authorization":"Bearer personal-key-secured","X-Filter":{}}});
		expect(await server.support.tickets.create({} as SupportTicketRequest)).to.deep.equal({"verb":"post","route":"https://api.linode.com/v4/support/tickets","body":{},"headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets(1).get()).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets/1","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets(1).attachments()).to.deep.equal({"verb":"post","route":"https://api.linode.com/v4/support/tickets/1/attachments","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets(1).replies.list()).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets/1/replies","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets(1).replies.list(1)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets/1/replies","query":"?page=1","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets(1).replies.list(1, 50)).to.deep.equal({"verb":"get","route":"https://api.linode.com/v4/support/tickets/1/replies","query":"?page=1&page_size=50","headers":{"Authorization":"Bearer personal-key-secured"}});
		expect(await server.support.tickets(1).replies.create({} as any)).to.deep.equal({"verb":"post","route":"https://api.linode.com/v4/support/tickets/1/replies","body":{},"headers":{"Authorization":"Bearer personal-key-secured"}});
	});
});
